name: PR Validation (Maven + JaCoCo)

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: my-app

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up JDK 17
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # 3. Optional: Clean Maven cache to avoid dependency issues
      - name: Clean Maven Repository
        run: mvn dependency:purge-local-repository clean

      # 4. Apply Spotless formatting
      - name: Apply Spotless Formatting
        run: mvn spotless:apply

      # 5. Spotless check
      - name: Spotless Check
        run: mvn spotless:check

      # 6. Run Checkstyle
      - name: Run Checkstyle
        run: mvn checkstyle:check

      # 7. Build, Test & Generate Coverage
      - name: Build, Test & Coverage
        run: mvn -B clean test jacoco:report -U

      # 8. Extract JaCoCo Coverage %
      - name: Extract Coverage
        id: coverage
        run: |
          XML="target/site/jacoco/jacoco.xml"
          if [ ! -f "$XML" ]; then
            echo "coverage=0.0" >> $GITHUB_OUTPUT
          else
            COV=$(grep -m1 '<counter type="LINE"' $XML | sed -E 's/.*missed="([0-9]+)".*covered="([0-9]+)".*/\1 \2/' | awk '{total=$1+$2; if(total==0){print 0}else{print ($2*100/total)}}')
            echo "coverage=$COV" >> $GITHUB_OUTPUT
          fi

      # 9. Post Coverage & Test Results as PR Comment using PAT
      - name: Post Coverage to PR
        uses: peter-evans/create-or-update-comment@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ### ✅ Build & Test Passed
            📊 Line coverage: **${{ steps.coverage.outputs.coverage }}%**

      # 10. Validate PR Description (JIRA ID)
      - name: Validate PR Description
        env:
          BODY: ${{ github.event.pull_request.body }}
        run: |
          if echo "$BODY" | grep -Eq 'JIRA-[0-9]+'; then
            echo "✅ JIRA ID found in PR description"
          else
            echo "❌ Missing JIRA ID in PR description"
            exit 1

      # 11. Validate PR Labels
      - name: Check PR Labels
        env:
          LABELS: ${{ toJson(github.event.pull_request.labels) }}
        run: |
          if [ "$LABELS" = "[]" ]; then
            echo "❌ No labels found on PR"
            exit 1
          else
            echo "✅ Labels present"
          fi
