name: PR Validation

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up JDK 11 (compatible with fmt-maven-plugin 2.11)
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '11'

      # 3. Maven build and test
      - name: Build and Test
        run: mvn clean test

      # 4. Check formatting and linting
      - name: Check Code Formatting
        run: mvn fmt:check

      - name: Lint Code
        run: mvn checkstyle:check

      # 5. Update PR with Maven test results
      - name: Publish Maven Test Results
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            ### Maven Test Results
            Build and tests passed ✅
          recreate: true

      # 6. Optional: add PR description/JIRA/labels validation
      # (skip for now for simple demo)
