name: PR Validation

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up JDK 17
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # 3. Apply Spotless formatting
      - name: Apply Spotless Formatting
        run: mvn spotless:apply

      # 4. Run Spotless check
      - name: Spotless Check
        run: mvn spotless:check

      # 5. Run Checkstyle
      - name: Run Checkstyle
        run: mvn checkstyle:check

      # 6. Build and run tests
      - name: Build & Test
        run: mvn clean test

      # 7. JaCoCo code coverage
      - name: Code Coverage
        run: mvn jacoco:report

      # 8. Validate PR description for JIRA ID
      - name: Check PR Description for JIRA
        uses: juliangruber/validate-pr-description@v1
        with:
          pattern: 'JIRA-\d+'
          fail-message: 'PR description must include a JIRA ID'

      # 9. Validate PR labels
      - name: Check PR Labels
        run: |
          python3 .github/scripts/validate_pr_labels.py
